# Copyright (c) 2021-2022 Luis Peñaranda. All rights reserved.
#
# This file is part of empdfer.
#
# Empdfer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Empdfer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with empdfer.  If not, see <http://www.gnu.org/licenses/>.

name: empdfer # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Embed images into a PDf # 79 char long summary
description: |
  Empdfer is a command-line tool which embeds graphic images into a PDF.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  paddlefish:
    source: https://github.com/luis4a0/paddlefish.git
    plugin: make
    make-parameters:
    - libpaddlefish.a
    organize:
      libpaddlefish.a: lib/
    build-packages:
    - g++-10
    - make
    - zlib1g-dev
    stage-packages:
    - zlib1g
  empdfer:
    plugin: make
    make-parameters:
    - empdfer
    override-build: |
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp empdfer $SNAPCRAFT_PART_INSTALL/bin
    organize:
      empdfer: bin/
    after:
    - paddlefish
    source: .
    build-packages:
    - g++-10
    - make
    - zlib1g-dev
    - libjpeg-dev
    - libpng-dev
    stage-packages:
    - zlib1g
    - libjpeg8
    - libpng16-16

apps:
  empdfer:
    command: bin/empdfer
    plugs:
    - home
    - removable-media
