# Copyright (c) 2021-2022 Luis Peñaranda. All rights reserved.
#
# This file is part of empdfer.
#
# Empdfer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Empdfer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with empdfer.  If not, see <http://www.gnu.org/licenses/>.

name: empdfer # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.9.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Embed images into a PDF # 79 char long summary
description: |
  Empdfer is a command-line tool which embeds graphic images into a PDF.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  paddlefish:
    source: https://github.com/luis4a0/paddlefish.git
    plugin: cmake
    cmake-parameters:
    - -DCMAKE_CXX_COMPILER=/usr/bin/g++-12
    - -DCMAKE_BUILD_TYPE=Release
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DPADDLEFISH_USE_ZLIB=ON
    - -DPADDLEFISH_BUILD_EXAMPLES=OFF
    build-packages:
    - g++-12
    - zlib1g-dev
    stage-packages:
    - zlib1g
  empdfer:
    after:
    - paddlefish
    plugin: cmake
    cmake-parameters:
    - -DCMAKE_CXX_COMPILER=/usr/bin/g++-12
    - -DCMAKE_BUILD_TYPE=Release
    - -DCMAKE_INSTALL_PREFIX=/
    - -DPADDLEFISH_INCLUDE_DIR=/root/parts/paddlefish/install/usr/include
    - -DPADDLEFISH_LIBRARY_RELEASE=/root/parts/paddlefish/install/usr/lib/x86_64-linux-gnu/libpaddlefish.so
    - -DEMPDFER_USE_PNG=ON
    source: .
    build-packages:
    - g++-12
    - libjpeg-dev
    - libpng-dev
    stage-packages:
    - libjpeg8
    - libpng16-16

apps:
  empdfer:
    command: bin/empdfer
    plugs:
    - home
    - removable-media
